// Auto-generated by @TypeScriptEndpoint — do not edit

import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { AnimalType } from '../enums/animal-type.enum';
import { Gender } from '../enums/gender.enum';
import { AnimalDto } from '../models/animal-dto.model';
import { CreateAndEditAnimalDTO } from '../models/create-and-edit-animal-dto.model';

@Injectable({ providedIn: 'root' })
export class AnimalService {
  private http = inject(HttpClient);
  private baseUrl = `${environment.apiUrl}/animals`;

  register(body: CreateAndEditAnimalDTO): Observable<AnimalDto> {
    return this.http.post<AnimalDto>(this.baseUrl, body);
  }

  findAll(params?: { type?: AnimalType; gender?: Gender }): Observable<AnimalDto[]> {
    let httpParams = new HttpParams();
    if (params?.type != null) httpParams = httpParams.set('type', String(params.type));
    if (params?.gender != null) httpParams = httpParams.set('gender', String(params.gender));
    return this.http.get<AnimalDto[]>(this.baseUrl, { params: httpParams });
  }

  findByTagNo(tagNo: string): Observable<AnimalDto> {
    return this.http.get<AnimalDto>(`${this.baseUrl}/${tagNo}`);
  }

  findOffspring(tagNo: string): Observable<AnimalDto[]> {
    return this.http.get<AnimalDto[]>(`${this.baseUrl}/${tagNo}/offspring`);
  }

  update(tagNo: string, body: CreateAndEditAnimalDTO): Observable<AnimalDto> {
    return this.http.put<AnimalDto>(`${this.baseUrl}/${tagNo}`, body);
  }

  delete(tagNo: string): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/${tagNo}`);
  }
}
