// Auto-generated by @TypeScriptEndpoint — do not edit

import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { FinanceCategory } from '../enums/finance-category.enum';
import { TransactionType } from '../enums/transaction-type.enum';
import { CreateAndUpdateFinanceDTO } from '../models/create-and-update-finance-dto.model';
import { FinanceDto } from '../models/finance-dto.model';
import { FinanceSummaryDto } from '../models/finance-summary-dto.model';

@Injectable({ providedIn: 'root' })
export class FinanceService {
  private http = inject(HttpClient);
  private baseUrl = `${environment.apiUrl}/finances`;

  create(body: CreateAndUpdateFinanceDTO): Observable<FinanceDto> {
    return this.http.post<FinanceDto>(this.baseUrl, body);
  }

  findAll(params?: { type?: TransactionType; category?: FinanceCategory }): Observable<FinanceDto[]> {
    let httpParams = new HttpParams();
    if (params?.type != null) httpParams = httpParams.set('type', String(params.type));
    if (params?.category != null) httpParams = httpParams.set('category', String(params.category));
    return this.http.get<FinanceDto[]>(this.baseUrl, { params: httpParams });
  }

  findById(id: number): Observable<FinanceDto> {
    return this.http.get<FinanceDto>(`${this.baseUrl}/${id}`);
  }

  findByAnimal(tagNo: string): Observable<FinanceDto[]> {
    return this.http.get<FinanceDto[]>(`${this.baseUrl}/animal/${tagNo}`);
  }

  findByDateRange(from: string, to: string): Observable<FinanceDto[]> {
    let httpParams = new HttpParams();
    httpParams = httpParams.set('from', String(from));
    httpParams = httpParams.set('to', String(to));
    return this.http.get<FinanceDto[]>(`${this.baseUrl}/date-range`, { params: httpParams });
  }

  getSummary(): Observable<FinanceSummaryDto> {
    return this.http.get<FinanceSummaryDto>(`${this.baseUrl}/summary`);
  }

  getSummaryForPeriod(from: string, to: string): Observable<FinanceSummaryDto> {
    let httpParams = new HttpParams();
    httpParams = httpParams.set('from', String(from));
    httpParams = httpParams.set('to', String(to));
    return this.http.get<FinanceSummaryDto>(`${this.baseUrl}/summary/period`, { params: httpParams });
  }

  getAnimalSummary(tagNo: string): Observable<FinanceSummaryDto> {
    return this.http.get<FinanceSummaryDto>(`${this.baseUrl}/summary/animal/${tagNo}`);
  }

  update(id: number, body: CreateAndUpdateFinanceDTO): Observable<FinanceDto> {
    return this.http.put<FinanceDto>(`${this.baseUrl}/${id}`, body);
  }

  delete(id: number): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/${id}`);
  }
}
