// Auto-generated by @TypeScriptEndpoint — do not edit

import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { RecordStatus } from '../enums/record-status.enum';
import { CreateAndUpdateHealthRecordDto } from '../models/create-and-update-health-record-dto.model';
import { HealthRecordDto } from '../models/health-record-dto.model';

@Injectable({ providedIn: 'root' })
export class HealthRecordService {
  private http = inject(HttpClient);
  private baseUrl = `${environment.apiUrl}/health-records`;

  create(body: CreateAndUpdateHealthRecordDto): Observable<HealthRecordDto> {
    return this.http.post<HealthRecordDto>(this.baseUrl, body);
  }

  findAll(params?: { status?: RecordStatus }): Observable<HealthRecordDto[]> {
    let httpParams = new HttpParams();
    if (params?.status != null) httpParams = httpParams.set('status', String(params.status));
    return this.http.get<HealthRecordDto[]>(this.baseUrl, { params: httpParams });
  }

  findById(id: number): Observable<HealthRecordDto> {
    return this.http.get<HealthRecordDto>(`${this.baseUrl}/${id}`);
  }

  findByAnimal(tagNo: string): Observable<HealthRecordDto[]> {
    return this.http.get<HealthRecordDto[]>(`${this.baseUrl}/animal/${tagNo}`);
  }

  findOverdue(): Observable<HealthRecordDto[]> {
    return this.http.get<HealthRecordDto[]>(`${this.baseUrl}/overdue`);
  }

  findUpcoming(params?: { daysAhead?: number }): Observable<HealthRecordDto[]> {
    let httpParams = new HttpParams();
    if (params?.daysAhead != null) httpParams = httpParams.set('daysAhead', String(params.daysAhead));
    return this.http.get<HealthRecordDto[]>(`${this.baseUrl}/upcoming`, { params: httpParams });
  }

  update(id: number, body: CreateAndUpdateHealthRecordDto): Observable<HealthRecordDto> {
    return this.http.put<HealthRecordDto>(`${this.baseUrl}/${id}`, body);
  }

  complete(id: number): Observable<HealthRecordDto> {
    return this.http.patch<HealthRecordDto>(`${this.baseUrl}/${id}/complete`, null);
  }

  delete(id: number): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/${id}`);
  }
}
