// Auto-generated by @TypeScriptEndpoint — do not edit

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { TreatmentDto } from '../models/treatment-dto.model';

@Injectable({ providedIn: 'root' })
export class TreatmentService {
  private http = inject(HttpClient);
  private baseUrl = `${environment.apiUrl}/treatments`;

  create(body: TreatmentDto): Observable<TreatmentDto> {
    return this.http.post<TreatmentDto>(this.baseUrl, body);
  }

  findAll(): Observable<TreatmentDto[]> {
    return this.http.get<TreatmentDto[]>(this.baseUrl);
  }

  findById(id: number): Observable<TreatmentDto> {
    return this.http.get<TreatmentDto>(`${this.baseUrl}/${id}`);
  }

  update(id: number, body: TreatmentDto): Observable<TreatmentDto> {
    return this.http.put<TreatmentDto>(`${this.baseUrl}/${id}`, body);
  }

  delete(id: number): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/${id}`);
  }
}
