// Auto-generated by @TypeScriptEndpoint — do not edit

import { AnimalStatus } from '../enums/animal-status.enum';
import { AnimalType } from '../enums/animal-type.enum';
import { Color } from '../enums/color.enum';
import { Gender } from '../enums/gender.enum';
import { AnimalOwnerDto } from './animal-owner-dto.model';

export interface AnimalDto {
  tagNo: string;
  name: string;
  color: Color;
  type: AnimalType;
  status: AnimalStatus;
  gender: Gender;
  dateOfBirth: string;
  birthWeight: number;
  currentWeight: number;
  motherTagNo: string;
  fatherTagNo: string;
  owners: AnimalOwnerDto[];
}
