// Auto-generated by @TypeScriptEndpoint — do not edit

import { FinanceCategory } from '../enums/finance-category.enum';
import { TransactionType } from '../enums/transaction-type.enum';

export interface CreateAndUpdateFinanceDTO {
  transactionType: TransactionType;
  category: FinanceCategory;
  amount: number;
  date: string;
  description: string;
  animalTagNo: string;
  referenceId: string;
}
