// Auto-generated by @TypeScriptEndpoint — do not edit

import { RecordStatus } from '../enums/record-status.enum';

export interface CreateAndUpdateHealthRecordDto {
  animalTagNo: string;
  date: string;
  treatmentId: number;
  dosage: string;
  nextDue: string;
  notes: string;
  status: RecordStatus;
  overdue: boolean;
}
