INSERT INTO graze.treatment (name, default_interval_days)
VALUES ('CDT vaccine (Clostridium perfringens types C & D + Tetanus)', 365),
       ('CDT booster for kids', 30),
       ('Deworming (internal parasites)', 90),
       ('Coccidiosis prevention/treatment', 30),
       ('External parasite control (ticks lice mites)', 60),
       ('Vitamin and mineral supplement', 30),
       ('Selenium and Vitamin E supplement', 180),
       ('Multivitamin injection during stress', 60),
       ('Foot trimming', 90),
       ('Foot rot inspection and treatment', 30),
       ('Pneumonia vaccination', 365),
       ('Brucellosis vaccination', 365),
       ('Pasteurella vaccination', 365),
       ('Anthrax vaccination (risk areas)', 365),
       ('Rift Valley Fever vaccination (risk areas)', 365),
       ('Tick borne disease inspection', 30),
       ('Wound and injury inspection', 7),
       ('Mastitis check for lactating does', 30),
       ('Body condition scoring check', 30),
       ('Pregnancy diagnosis check', 60),
       ('Pregnancy nutrition check (late pregnancy)', 30),
       ('Kidding preparation health check', 30),
       ('Post-kidding health check', 7),
       ('Newborn kid navel iodine treatment', 1),
       ('Newborn kid vitamin injection', 1),
       ('Newborn kid selenium supplement', 1),
       ('Newborn kid colostrum check', 1),
       ('Disbudding (if done)', 7),
       ('Castration check for male kids', 7),
       ('Growth and weight monitoring', 30),
       ('Hoof abscess treatment check', 30),
       ('Eye infection treatment check (pink eye)', 30),
       ('Internal parasite fecal egg count test', 60),
       ('Water quality inspection', 30),
       ('Feed nutrition inspection', 30),
       ('Heat stress monitoring', 7),
       ('Cold stress monitoring', 7),
       ('Breeding buck fertility check', 180),
       ('Breeding health check before mating', 30),
       ('Quarantine treatment for new goats', 14),
       ('Isolation monitoring for sick animals', 7),
       ('Vaccination record review', 365),
       ('General herd health inspection', 30);

