// Auto-generated by @TypeScriptEndpoint — do not edit

export enum FinanceCategory {
  VETERINARY = 'VETERINARY',
  FEED = 'FEED',
  MEDICATION = 'MEDICATION',
  SALE = 'SALE',
  PURCHASE = 'PURCHASE',
  EQUIPMENT = 'EQUIPMENT',
  LABOUR = 'LABOUR',
  SOFTWARE_HOSTING = 'SOFTWARE_HOSTING',
  OTHER = 'OTHER'
}
